//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVENTITYPROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPROJELER
    {
        public byte ID { get; set; }
        public string PROJEAD { get; set; }
        public string PROJEDETAY { get; set; }
        public string PROJERESİM { get; set; }
    }
}
